<?php
// Generated by Clipaza Installer — DO NOT EDIT MANUALLY
define('DB_HOST', '{{DB_HOST}}');
define('DB_PORT', '{{DB_PORT}}');
define('DB_NAME', '{{DB_NAME}}');
define('DB_USER', '{{DB_USER}}');
define('DB_PASS', '{{DB_PASS}}');
define('SITE_NAME', '{{SITE_NAME}}');
define('SITE_URL', '{{SITE_URL}}');
define('ADMIN_EMAIL', '{{ADMIN_EMAIL}}');
define('SMTP_HOST', '{{SMTP_HOST}}');
define('SMTP_PORT', '{{SMTP_PORT}}');
define('SMTP_USER', '{{SMTP_USER}}');
define('SMTP_PASS', '{{SMTP_PASS}}');
define('SMTP_ENCRYPTION', '{{SMTP_ENCRYPTION}}');
define('APP_KEY', '{{APP_KEY}}');
define('PAYSTACK_SECRET_KEY', ');
define('PAYSTACK_PUBLIC_KEY', ');
define('INSTALLED', true);
