-- Clipaza Database Schema
-- Generated by Clipaza Installer

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

-- Users table
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('admin','user','moderator') NOT NULL DEFAULT 'user',
  `status` enum('active','inactive','banned','pending') NOT NULL DEFAULT 'pending',
  `login_notifications` tinyint(1) NOT NULL DEFAULT 0,
  `email_verification_token` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_username` (`username`),
  UNIQUE KEY `uq_users_email` (`email`),
  KEY `idx_users_role` (`role`),
  KEY `idx_users_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Site settings
CREATE TABLE IF NOT EXISTS `site_settings` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_site_settings_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Security settings
CREATE TABLE IF NOT EXISTS `security_settings` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_security_settings_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Login attempts
CREATE TABLE IF NOT EXISTS `login_attempts` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `success` tinyint(1) NOT NULL DEFAULT 0,
  `attempted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_login_attempts_username` (`username`),
  KEY `idx_login_attempts_ip` (`ip_address`),
  KEY `idx_login_attempts_at` (`attempted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- IP blocks
CREATE TABLE IF NOT EXISTS `ip_blocks` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(45) NOT NULL,
  `block_type` enum('temporary','permanent') NOT NULL DEFAULT 'temporary',
  `blocked_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `blocked_until` datetime DEFAULT NULL,
  `reason` varchar(500) DEFAULT NULL,
  `created_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ip_blocks_ip` (`ip_address`),
  KEY `idx_ip_blocks_until` (`blocked_until`),
  KEY `fk_ip_blocks_user` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- IP whitelist
CREATE TABLE IF NOT EXISTS `ip_whitelist` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(45) NOT NULL,
  `user_id` int(11) UNSIGNED DEFAULT NULL,
  `successful_logins` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `last_seen` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ip_whitelist_ip` (`ip_address`),
  KEY `fk_ip_whitelist_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Account locks
CREATE TABLE IF NOT EXISTS `account_locks` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `locked_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `locked_until` datetime DEFAULT NULL,
  `lock_reason` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_account_locks_username` (`username`),
  KEY `idx_account_locks_until` (`locked_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Login history
CREATE TABLE IF NOT EXISTS `login_history` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED DEFAULT NULL,
  `username` varchar(100) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `action` varchar(50) NOT NULL,
  `details` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_login_history_user` (`user_id`),
  KEY `idx_login_history_ip` (`ip_address`),
  KEY `idx_login_history_action` (`action`),
  KEY `idx_login_history_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Country rules
CREATE TABLE IF NOT EXISTS `country_rules` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_code` char(2) NOT NULL,
  `country_name` varchar(100) NOT NULL,
  `status` enum('not_specified','whitelist','blacklist') NOT NULL DEFAULT 'not_specified',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_country_rules_code` (`country_code`),
  KEY `idx_country_rules_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Email queue
CREATE TABLE IF NOT EXISTS `email_queue` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `to_email` varchar(255) NOT NULL,
  `subject` varchar(500) NOT NULL,
  `body` text NOT NULL,
  `sent` tinyint(1) NOT NULL DEFAULT 0,
  `attempts` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sent_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_email_queue_sent` (`sent`),
  KEY `idx_email_queue_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Contests
CREATE TABLE IF NOT EXISTS `contests` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `prize_pool` decimal(10,2) NOT NULL DEFAULT 0.00,
  `status` enum('draft','active','ended','cancelled') NOT NULL DEFAULT 'draft',
  `start_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_contests_status` (`status`),
  KEY `idx_contests_dates` (`start_date`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Contest entries
CREATE TABLE IF NOT EXISTS `contest_entries` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contest_id` int(11) UNSIGNED NOT NULL,
  `user_id` int(11) UNSIGNED NOT NULL,
  `clip_url` varchar(2000) NOT NULL,
  `votes` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `submitted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_entries_contest` (`contest_id`),
  KEY `fk_entries_user` (`user_id`),
  KEY `idx_entries_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Transactions
CREATE TABLE IF NOT EXISTS `transactions` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `type` enum('credit','debit','withdrawal','refund') NOT NULL,
  `status` enum('pending','completed','failed','cancelled') NOT NULL DEFAULT 'pending',
  `reference` varchar(255) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_transactions_user` (`user_id`),
  KEY `idx_transactions_type` (`type`),
  KEY `idx_transactions_status` (`status`),
  KEY `idx_transactions_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Waitlist
CREATE TABLE IF NOT EXISTS `waitlist` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_waitlist_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Default security settings
INSERT INTO `security_settings` (`setting_key`, `setting_value`) VALUES
('ip_protection_enabled', '1'),
('ip_period_minutes', '15'),
('ip_max_failures', '10'),
('username_protection_enabled', '1'),
('username_period_minutes', '30'),
('username_max_failures', '5'),
('block_duration_minutes', '60'),
('notify_on_block', '1'),
('notify_on_lock', '1'),
('log_retention_days', '90'),
('two_factor_enabled', '0'),
('captcha_enabled', '0'),
('captcha_threshold', '3'),
('protect_local_only', '0'),
('allow_lock_admin', '0'),
('ip_block_duration_option', '1day'),
('notify_admin_login_unknown_ip', '0'),
('notify_brute_force_with_username', '0')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);

-- Default site settings
INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES
('site_name', 'Clipaza'),
('site_url', 'http://localhost'),
('admin_email', 'admin@example.com'),
('maintenance_mode', '0'),
('registration_enabled', '1'),
('timezone', 'UTC'),
('site_logo', ''),
('site_favicon', ''),
('seo_title', ''),
('seo_description', ''),
('seo_keywords', ''),
('og_image_url', ''),
('custom_header_code', ''),
('adsense_code', ''),
('ads_txt_content', '')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);

-- Additional site settings for payment/contest features
INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES
('paystack_public_key', ''),
('paystack_secret_key', ''),
('platform_fee_percent', '10'),
('youtube_api_key', ''),
('min_contest_prize', '5000'),
('max_contest_days', '30')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);

-- Country rules for all ~250 countries
INSERT INTO `country_rules` (`country_code`, `country_name`, `status`) VALUES
('AF', 'Afghanistan', 'not_specified'),
('AX', 'Åland Islands', 'not_specified'),
('AL', 'Albania', 'not_specified'),
('DZ', 'Algeria', 'not_specified'),
('AS', 'American Samoa', 'not_specified'),
('AD', 'Andorra', 'not_specified'),
('AO', 'Angola', 'not_specified'),
('AI', 'Anguilla', 'not_specified'),
('AQ', 'Antarctica', 'not_specified'),
('AG', 'Antigua and Barbuda', 'not_specified'),
('AR', 'Argentina', 'not_specified'),
('AM', 'Armenia', 'not_specified'),
('AW', 'Aruba', 'not_specified'),
('AU', 'Australia', 'not_specified'),
('AT', 'Austria', 'not_specified'),
('AZ', 'Azerbaijan', 'not_specified'),
('BS', 'Bahamas', 'not_specified'),
('BH', 'Bahrain', 'not_specified'),
('BD', 'Bangladesh', 'not_specified'),
('BB', 'Barbados', 'not_specified'),
('BY', 'Belarus', 'not_specified'),
('BE', 'Belgium', 'not_specified'),
('BZ', 'Belize', 'not_specified'),
('BJ', 'Benin', 'not_specified'),
('BM', 'Bermuda', 'not_specified'),
('BT', 'Bhutan', 'not_specified'),
('BO', 'Bolivia', 'not_specified'),
('BQ', 'Bonaire, Sint Eustatius and Saba', 'not_specified'),
('BA', 'Bosnia and Herzegovina', 'not_specified'),
('BW', 'Botswana', 'not_specified'),
('BV', 'Bouvet Island', 'not_specified'),
('BR', 'Brazil', 'not_specified'),
('IO', 'British Indian Ocean Territory', 'not_specified'),
('BN', 'Brunei Darussalam', 'not_specified'),
('BG', 'Bulgaria', 'not_specified'),
('BF', 'Burkina Faso', 'not_specified'),
('BI', 'Burundi', 'not_specified'),
('CV', 'Cabo Verde', 'not_specified'),
('KH', 'Cambodia', 'not_specified'),
('CM', 'Cameroon', 'not_specified'),
('CA', 'Canada', 'not_specified'),
('KY', 'Cayman Islands', 'not_specified'),
('CF', 'Central African Republic', 'not_specified'),
('TD', 'Chad', 'not_specified'),
('CL', 'Chile', 'not_specified'),
('CN', 'China', 'not_specified'),
('CX', 'Christmas Island', 'not_specified'),
('CC', 'Cocos (Keeling) Islands', 'not_specified'),
('CO', 'Colombia', 'not_specified'),
('KM', 'Comoros', 'not_specified'),
('CG', 'Congo', 'not_specified'),
('CD', 'Congo, Democratic Republic of the', 'not_specified'),
('CK', 'Cook Islands', 'not_specified'),
('CR', 'Costa Rica', 'not_specified'),
('CI', 'Côte d''Ivoire', 'not_specified'),
('HR', 'Croatia', 'not_specified'),
('CU', 'Cuba', 'not_specified'),
('CW', 'Curaçao', 'not_specified'),
('CY', 'Cyprus', 'not_specified'),
('CZ', 'Czechia', 'not_specified'),
('DK', 'Denmark', 'not_specified'),
('DJ', 'Djibouti', 'not_specified'),
('DM', 'Dominica', 'not_specified'),
('DO', 'Dominican Republic', 'not_specified'),
('EC', 'Ecuador', 'not_specified'),
('EG', 'Egypt', 'not_specified'),
('SV', 'El Salvador', 'not_specified'),
('GQ', 'Equatorial Guinea', 'not_specified'),
('ER', 'Eritrea', 'not_specified'),
('EE', 'Estonia', 'not_specified'),
('SZ', 'Eswatini', 'not_specified'),
('ET', 'Ethiopia', 'not_specified'),
('FK', 'Falkland Islands (Malvinas)', 'not_specified'),
('FO', 'Faroe Islands', 'not_specified'),
('FJ', 'Fiji', 'not_specified'),
('FI', 'Finland', 'not_specified'),
('FR', 'France', 'not_specified'),
('GF', 'French Guiana', 'not_specified'),
('PF', 'French Polynesia', 'not_specified'),
('TF', 'French Southern Territories', 'not_specified'),
('GA', 'Gabon', 'not_specified'),
('GM', 'Gambia', 'not_specified'),
('GE', 'Georgia', 'not_specified'),
('DE', 'Germany', 'not_specified'),
('GH', 'Ghana', 'not_specified'),
('GI', 'Gibraltar', 'not_specified'),
('GR', 'Greece', 'not_specified'),
('GL', 'Greenland', 'not_specified'),
('GD', 'Grenada', 'not_specified'),
('GP', 'Guadeloupe', 'not_specified'),
('GU', 'Guam', 'not_specified'),
('GT', 'Guatemala', 'not_specified'),
('GG', 'Guernsey', 'not_specified'),
('GN', 'Guinea', 'not_specified'),
('GW', 'Guinea-Bissau', 'not_specified'),
('GY', 'Guyana', 'not_specified'),
('HT', 'Haiti', 'not_specified'),
('HM', 'Heard Island and McDonald Islands', 'not_specified'),
('VA', 'Holy See', 'not_specified'),
('HN', 'Honduras', 'not_specified'),
('HK', 'Hong Kong', 'not_specified'),
('HU', 'Hungary', 'not_specified'),
('IS', 'Iceland', 'not_specified'),
('IN', 'India', 'not_specified'),
('ID', 'Indonesia', 'not_specified'),
('IR', 'Iran, Islamic Republic of', 'not_specified'),
('IQ', 'Iraq', 'not_specified'),
('IE', 'Ireland', 'not_specified'),
('IM', 'Isle of Man', 'not_specified'),
('IL', 'Israel', 'not_specified'),
('IT', 'Italy', 'not_specified'),
('JM', 'Jamaica', 'not_specified'),
('JP', 'Japan', 'not_specified'),
('JE', 'Jersey', 'not_specified'),
('JO', 'Jordan', 'not_specified'),
('KZ', 'Kazakhstan', 'not_specified'),
('KE', 'Kenya', 'not_specified'),
('KI', 'Kiribati', 'not_specified'),
('KP', 'Korea, Democratic People''s Republic of', 'not_specified'),
('KR', 'Korea, Republic of', 'not_specified'),
('KW', 'Kuwait', 'not_specified'),
('KG', 'Kyrgyzstan', 'not_specified'),
('LA', 'Lao People''s Democratic Republic', 'not_specified'),
('LV', 'Latvia', 'not_specified'),
('LB', 'Lebanon', 'not_specified'),
('LS', 'Lesotho', 'not_specified'),
('LR', 'Liberia', 'not_specified'),
('LY', 'Libya', 'not_specified'),
('LI', 'Liechtenstein', 'not_specified'),
('LT', 'Lithuania', 'not_specified'),
('LU', 'Luxembourg', 'not_specified'),
('MO', 'Macao', 'not_specified'),
('MG', 'Madagascar', 'not_specified'),
('MW', 'Malawi', 'not_specified'),
('MY', 'Malaysia', 'not_specified'),
('MV', 'Maldives', 'not_specified'),
('ML', 'Mali', 'not_specified'),
('MT', 'Malta', 'not_specified'),
('MH', 'Marshall Islands', 'not_specified'),
('MQ', 'Martinique', 'not_specified'),
('MR', 'Mauritania', 'not_specified'),
('MU', 'Mauritius', 'not_specified'),
('YT', 'Mayotte', 'not_specified'),
('MX', 'Mexico', 'not_specified'),
('FM', 'Micronesia, Federated States of', 'not_specified'),
('MD', 'Moldova, Republic of', 'not_specified'),
('MC', 'Monaco', 'not_specified'),
('MN', 'Mongolia', 'not_specified'),
('ME', 'Montenegro', 'not_specified'),
('MS', 'Montserrat', 'not_specified'),
('MA', 'Morocco', 'not_specified'),
('MZ', 'Mozambique', 'not_specified'),
('MM', 'Myanmar', 'not_specified'),
('NA', 'Namibia', 'not_specified'),
('NR', 'Nauru', 'not_specified'),
('NP', 'Nepal', 'not_specified'),
('NL', 'Netherlands', 'not_specified'),
('NC', 'New Caledonia', 'not_specified'),
('NZ', 'New Zealand', 'not_specified'),
('NI', 'Nicaragua', 'not_specified'),
('NE', 'Niger', 'not_specified'),
('NG', 'Nigeria', 'not_specified'),
('NU', 'Niue', 'not_specified'),
('NF', 'Norfolk Island', 'not_specified'),
('MK', 'North Macedonia', 'not_specified'),
('MP', 'Northern Mariana Islands', 'not_specified'),
('NO', 'Norway', 'not_specified'),
('OM', 'Oman', 'not_specified'),
('PK', 'Pakistan', 'not_specified'),
('PW', 'Palau', 'not_specified'),
('PS', 'Palestine, State of', 'not_specified'),
('PA', 'Panama', 'not_specified'),
('PG', 'Papua New Guinea', 'not_specified'),
('PY', 'Paraguay', 'not_specified'),
('PE', 'Peru', 'not_specified'),
('PH', 'Philippines', 'not_specified'),
('PN', 'Pitcairn', 'not_specified'),
('PL', 'Poland', 'not_specified'),
('PT', 'Portugal', 'not_specified'),
('PR', 'Puerto Rico', 'not_specified'),
('QA', 'Qatar', 'not_specified'),
('RE', 'Réunion', 'not_specified'),
('RO', 'Romania', 'not_specified'),
('RU', 'Russian Federation', 'not_specified'),
('RW', 'Rwanda', 'not_specified'),
('BL', 'Saint Barthélemy', 'not_specified'),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'not_specified'),
('KN', 'Saint Kitts and Nevis', 'not_specified'),
('LC', 'Saint Lucia', 'not_specified'),
('MF', 'Saint Martin (French part)', 'not_specified'),
('PM', 'Saint Pierre and Miquelon', 'not_specified'),
('VC', 'Saint Vincent and the Grenadines', 'not_specified'),
('WS', 'Samoa', 'not_specified'),
('SM', 'San Marino', 'not_specified'),
('ST', 'Sao Tome and Principe', 'not_specified'),
('SA', 'Saudi Arabia', 'not_specified'),
('SN', 'Senegal', 'not_specified'),
('RS', 'Serbia', 'not_specified'),
('SC', 'Seychelles', 'not_specified'),
('SL', 'Sierra Leone', 'not_specified'),
('SG', 'Singapore', 'not_specified'),
('SX', 'Sint Maarten (Dutch part)', 'not_specified'),
('SK', 'Slovakia', 'not_specified'),
('SI', 'Slovenia', 'not_specified'),
('SB', 'Solomon Islands', 'not_specified'),
('SO', 'Somalia', 'not_specified'),
('ZA', 'South Africa', 'not_specified'),
('GS', 'South Georgia and the South Sandwich Islands', 'not_specified'),
('SS', 'South Sudan', 'not_specified'),
('ES', 'Spain', 'not_specified'),
('LK', 'Sri Lanka', 'not_specified'),
('SD', 'Sudan', 'not_specified'),
('SR', 'Suriname', 'not_specified'),
('SJ', 'Svalbard and Jan Mayen', 'not_specified'),
('SE', 'Sweden', 'not_specified'),
('CH', 'Switzerland', 'not_specified'),
('SY', 'Syrian Arab Republic', 'not_specified'),
('TW', 'Taiwan, Province of China', 'not_specified'),
('TJ', 'Tajikistan', 'not_specified'),
('TZ', 'Tanzania, United Republic of', 'not_specified'),
('TH', 'Thailand', 'not_specified'),
('TL', 'Timor-Leste', 'not_specified'),
('TG', 'Togo', 'not_specified'),
('TK', 'Tokelau', 'not_specified'),
('TO', 'Tonga', 'not_specified'),
('TT', 'Trinidad and Tobago', 'not_specified'),
('TN', 'Tunisia', 'not_specified'),
('TR', 'Turkey', 'not_specified'),
('TM', 'Turkmenistan', 'not_specified'),
('TC', 'Turks and Caicos Islands', 'not_specified'),
('TV', 'Tuvalu', 'not_specified'),
('UG', 'Uganda', 'not_specified'),
('UA', 'Ukraine', 'not_specified'),
('AE', 'United Arab Emirates', 'not_specified'),
('GB', 'United Kingdom of Great Britain and Northern Ireland', 'not_specified'),
('UM', 'United States Minor Outlying Islands', 'not_specified'),
('US', 'United States of America', 'not_specified'),
('UY', 'Uruguay', 'not_specified'),
('UZ', 'Uzbekistan', 'not_specified'),
('VU', 'Vanuatu', 'not_specified'),
('VE', 'Venezuela, Bolivarian Republic of', 'not_specified'),
('VN', 'Viet Nam', 'not_specified'),
('VG', 'Virgin Islands (British)', 'not_specified'),
('VI', 'Virgin Islands (U.S.)', 'not_specified'),
('WF', 'Wallis and Futuna', 'not_specified'),
('EH', 'Western Sahara', 'not_specified'),
('YE', 'Yemen', 'not_specified'),
('ZM', 'Zambia', 'not_specified'),
('ZW', 'Zimbabwe', 'not_specified')
ON DUPLICATE KEY UPDATE country_name = VALUES(country_name);

SET foreign_key_checks = 1;

-- ===================== CLIPAZA PLATFORM EXTENSIONS =====================

-- User profiles (extends users table)
CREATE TABLE IF NOT EXISTS `user_profiles` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int UNSIGNED NOT NULL,
  `display_name` varchar(100) DEFAULT NULL,
  `bio` text DEFAULT NULL,
  `youtube_handle` varchar(100) DEFAULT NULL,
  `youtube_channel_id` varchar(100) DEFAULT NULL,
  `tiktok_handle` varchar(100) DEFAULT NULL,
  `instagram_handle` varchar(100) DEFAULT NULL,
  `facebook_handle` varchar(100) DEFAULT NULL,
  `active_mode` enum('creator','clipper') NOT NULL DEFAULT 'clipper',
  `wallet_balance` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_earned` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_spent` decimal(12,2) NOT NULL DEFAULT 0.00,
  `avatar` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_profiles_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Enhanced contests table
ALTER TABLE `contests`
  ADD COLUMN IF NOT EXISTS `creator_id` int UNSIGNED DEFAULT NULL AFTER `id`,
  ADD COLUMN IF NOT EXISTS `youtube_url` varchar(2000) DEFAULT NULL AFTER `creator_id`,
  ADD COLUMN IF NOT EXISTS `youtube_video_id` varchar(50) DEFAULT NULL AFTER `youtube_url`,
  ADD COLUMN IF NOT EXISTS `youtube_title` varchar(500) DEFAULT NULL AFTER `youtube_video_id`,
  ADD COLUMN IF NOT EXISTS `youtube_thumbnail` varchar(2000) DEFAULT NULL AFTER `youtube_title`,
  ADD COLUMN IF NOT EXISTS `must_subscribe` tinyint(1) NOT NULL DEFAULT 0 AFTER `youtube_thumbnail`,
  ADD COLUMN IF NOT EXISTS `must_like` tinyint(1) NOT NULL DEFAULT 0 AFTER `must_subscribe`,
  ADD COLUMN IF NOT EXISTS `must_comment` tinyint(1) NOT NULL DEFAULT 0 AFTER `must_like`,
  ADD COLUMN IF NOT EXISTS `clip_start_time` varchar(20) DEFAULT NULL AFTER `must_comment`,
  ADD COLUMN IF NOT EXISTS `clip_end_time` varchar(20) DEFAULT NULL AFTER `clip_start_time`,
  ADD COLUMN IF NOT EXISTS `clip_instructions` text DEFAULT NULL AFTER `clip_end_time`,
  ADD COLUMN IF NOT EXISTS `platform_fee` decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `prize_pool`,
  ADD COLUMN IF NOT EXISTS `total_amount` decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `platform_fee`,
  ADD COLUMN IF NOT EXISTS `escrow_status` enum('unfunded','funded','released','refunded') NOT NULL DEFAULT 'unfunded' AFTER `total_amount`,
  ADD COLUMN IF NOT EXISTS `paystack_reference` varchar(255) DEFAULT NULL AFTER `escrow_status`,
  ADD COLUMN IF NOT EXISTS `funded_at` datetime DEFAULT NULL AFTER `paystack_reference`;

ALTER TABLE `contests`
  ADD KEY IF NOT EXISTS `idx_contests_creator` (`creator_id`);

-- Contest platform prize splits
CREATE TABLE IF NOT EXISTS `contest_platforms` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `contest_id` int UNSIGNED NOT NULL,
  `platform` enum('tiktok','instagram','facebook') NOT NULL,
  `prize_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `winner_count` int UNSIGNED NOT NULL DEFAULT 3,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_contest_platform` (`contest_id`,`platform`),
  KEY `idx_cp_contest` (`contest_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Enhanced contest entries
ALTER TABLE `contest_entries`
  ADD COLUMN IF NOT EXISTS `platform` enum('tiktok','instagram','facebook') DEFAULT NULL AFTER `clip_url`,
  ADD COLUMN IF NOT EXISTS `view_count` bigint UNSIGNED NOT NULL DEFAULT 0 AFTER `platform`,
  ADD COLUMN IF NOT EXISTS `like_count` int UNSIGNED NOT NULL DEFAULT 0 AFTER `view_count`,
  ADD COLUMN IF NOT EXISTS `comment_count` int UNSIGNED NOT NULL DEFAULT 0 AFTER `like_count`,
  ADD COLUMN IF NOT EXISTS `disqualified` tinyint(1) NOT NULL DEFAULT 0 AFTER `comment_count`,
  ADD COLUMN IF NOT EXISTS `disqualify_reason` varchar(255) DEFAULT NULL AFTER `disqualified`,
  ADD COLUMN IF NOT EXISTS `verified_subscribe` tinyint(1) NOT NULL DEFAULT 0 AFTER `disqualify_reason`,
  ADD COLUMN IF NOT EXISTS `verified_like` tinyint(1) NOT NULL DEFAULT 0 AFTER `verified_subscribe`,
  ADD COLUMN IF NOT EXISTS `verified_comment` tinyint(1) NOT NULL DEFAULT 0 AFTER `verified_like`,
  ADD COLUMN IF NOT EXISTS `rank_position` int UNSIGNED DEFAULT NULL AFTER `verified_comment`,
  ADD COLUMN IF NOT EXISTS `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `submitted_at`;

-- Payouts (winner prize claims)
CREATE TABLE IF NOT EXISTS `payouts` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `contest_id` int UNSIGNED NOT NULL,
  `user_id` int UNSIGNED NOT NULL,
  `entry_id` int UNSIGNED NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `platform` enum('tiktok','instagram','facebook') NOT NULL,
  `rank_position` int UNSIGNED NOT NULL DEFAULT 1,
  `status` enum('pending','claimed','processing','completed','failed') NOT NULL DEFAULT 'pending',
  `bank_name` varchar(200) DEFAULT NULL,
  `bank_code` varchar(20) DEFAULT NULL,
  `account_number` varchar(20) DEFAULT NULL,
  `account_name` varchar(200) DEFAULT NULL,
  `nuban_verified` tinyint(1) NOT NULL DEFAULT 0,
  `paystack_reference` varchar(255) DEFAULT NULL,
  `paystack_transfer_code` varchar(255) DEFAULT NULL,
  `claimed_at` datetime DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_payouts_contest` (`contest_id`),
  KEY `idx_payouts_user` (`user_id`),
  KEY `idx_payouts_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Email verifications
CREATE TABLE IF NOT EXISTS `email_verifications` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int UNSIGNED NOT NULL,
  `token` varchar(100) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ev_token` (`token`),
  KEY `idx_ev_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Password reset tokens
CREATE TABLE IF NOT EXISTS `password_resets` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `token` varchar(100) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_pr_token` (`token`),
  KEY `idx_pr_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
