-- CLIPAZA Database Schema
-- Single-quotes inside string literals are escaped as two consecutive
-- single-quotes ('') per the SQL standard to avoid syntax errors.
-- Example: "Côte d'Ivoire" is stored as 'Côte d''Ivoire'.

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET time_zone = '+00:00';

-- -----------------------------------------------------------------------
-- Settings
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `settings` (
    `id`         INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `key_name`   VARCHAR(100)     NOT NULL,
    `key_value`  TEXT,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_key_name` (`key_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------
-- Users
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
    `id`           INT UNSIGNED  NOT NULL AUTO_INCREMENT,
    `username`     VARCHAR(60)   NOT NULL,
    `email`        VARCHAR(255)  NOT NULL,
    `password`     VARCHAR(255)  NOT NULL,
    `role`         ENUM('admin','user') NOT NULL DEFAULT 'user',
    `country_code` CHAR(2)       DEFAULT NULL,
    `created_at`   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------
-- Countries  (ISO 3166-1 alpha-2)
-- Note: apostrophes in country names are escaped as ''
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `countries` (
    `code`   CHAR(2)      NOT NULL,
    `name`   VARCHAR(100) NOT NULL,
    `status` VARCHAR(20)  NOT NULL DEFAULT 'not_specified',
    PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `countries` (`code`, `name`, `status`) VALUES
('AF', 'Afghanistan', 'not_specified'),
('AL', 'Albania', 'not_specified'),
('DZ', 'Algeria', 'not_specified'),
('AD', 'Andorra', 'not_specified'),
('AO', 'Angola', 'not_specified'),
('AG', 'Antigua and Barbuda', 'not_specified'),
('AR', 'Argentina', 'not_specified'),
('AM', 'Armenia', 'not_specified'),
('AU', 'Australia', 'not_specified'),
('AT', 'Austria', 'not_specified'),
('AZ', 'Azerbaijan', 'not_specified'),
('BS', 'Bahamas', 'not_specified'),
('BH', 'Bahrain', 'not_specified'),
('BD', 'Bangladesh', 'not_specified'),
('BB', 'Barbados', 'not_specified'),
('BY', 'Belarus', 'not_specified'),
('BE', 'Belgium', 'not_specified'),
('BZ', 'Belize', 'not_specified'),
('BJ', 'Benin', 'not_specified'),
('BT', 'Bhutan', 'not_specified'),
('BO', 'Bolivia', 'not_specified'),
('BA', 'Bosnia and Herzegovina', 'not_specified'),
('BW', 'Botswana', 'not_specified'),
('BR', 'Brazil', 'not_specified'),
('BN', 'Brunei', 'not_specified'),
('BG', 'Bulgaria', 'not_specified'),
('BF', 'Burkina Faso', 'not_specified'),
('BI', 'Burundi', 'not_specified'),
('CV', 'Cabo Verde', 'not_specified'),
('KH', 'Cambodia', 'not_specified'),
('CM', 'Cameroon', 'not_specified'),
('CA', 'Canada', 'not_specified'),
('CF', 'Central African Republic', 'not_specified'),
('TD', 'Chad', 'not_specified'),
('CL', 'Chile', 'not_specified'),
('CN', 'China', 'not_specified'),
('CO', 'Colombia', 'not_specified'),
('KM', 'Comoros', 'not_specified'),
('CD', 'Congo, Democratic Republic of the', 'not_specified'),
('CG', 'Congo, Republic of the', 'not_specified'),
('CR', 'Costa Rica', 'not_specified'),
-- Côte d'Ivoire: apostrophe escaped as '' (two single-quotes) per SQL standard
('CI', 'Côte d''Ivoire', 'not_specified'),
('HR', 'Croatia', 'not_specified'),
('CU', 'Cuba', 'not_specified'),
('CY', 'Cyprus', 'not_specified'),
('CZ', 'Czech Republic', 'not_specified'),
('DK', 'Denmark', 'not_specified'),
('DJ', 'Djibouti', 'not_specified'),
('DM', 'Dominica', 'not_specified'),
('DO', 'Dominican Republic', 'not_specified'),
('EC', 'Ecuador', 'not_specified'),
('EG', 'Egypt', 'not_specified'),
('SV', 'El Salvador', 'not_specified'),
('GQ', 'Equatorial Guinea', 'not_specified'),
('ER', 'Eritrea', 'not_specified'),
('EE', 'Estonia', 'not_specified'),
('SZ', 'Eswatini', 'not_specified'),
('ET', 'Ethiopia', 'not_specified'),
('FJ', 'Fiji', 'not_specified'),
('FI', 'Finland', 'not_specified'),
('FR', 'France', 'not_specified'),
('GA', 'Gabon', 'not_specified'),
('GM', 'Gambia', 'not_specified'),
('GE', 'Georgia', 'not_specified'),
('DE', 'Germany', 'not_specified'),
('GH', 'Ghana', 'not_specified'),
('GR', 'Greece', 'not_specified'),
('GD', 'Grenada', 'not_specified'),
('GT', 'Guatemala', 'not_specified'),
('GN', 'Guinea', 'not_specified'),
('GW', 'Guinea-Bissau', 'not_specified'),
('GY', 'Guyana', 'not_specified'),
('HT', 'Haiti', 'not_specified'),
('HN', 'Honduras', 'not_specified'),
('HU', 'Hungary', 'not_specified'),
('IS', 'Iceland', 'not_specified'),
('IN', 'India', 'not_specified'),
('ID', 'Indonesia', 'not_specified'),
('IR', 'Iran', 'not_specified'),
('IQ', 'Iraq', 'not_specified'),
('IE', 'Ireland', 'not_specified'),
('IL', 'Israel', 'not_specified'),
('IT', 'Italy', 'not_specified'),
('JM', 'Jamaica', 'not_specified'),
('JP', 'Japan', 'not_specified'),
('JO', 'Jordan', 'not_specified'),
('KZ', 'Kazakhstan', 'not_specified'),
('KE', 'Kenya', 'not_specified'),
('KI', 'Kiribati', 'not_specified'),
('KW', 'Kuwait', 'not_specified'),
('KG', 'Kyrgyzstan', 'not_specified'),
('LA', 'Laos', 'not_specified'),
('LV', 'Latvia', 'not_specified'),
('LB', 'Lebanon', 'not_specified'),
('LS', 'Lesotho', 'not_specified'),
('LR', 'Liberia', 'not_specified'),
('LY', 'Libya', 'not_specified'),
('LI', 'Liechtenstein', 'not_specified'),
('LT', 'Lithuania', 'not_specified'),
('LU', 'Luxembourg', 'not_specified'),
('MG', 'Madagascar', 'not_specified'),
('MW', 'Malawi', 'not_specified'),
('MY', 'Malaysia', 'not_specified'),
('MV', 'Maldives', 'not_specified'),
('ML', 'Mali', 'not_specified'),
('MT', 'Malta', 'not_specified'),
('MH', 'Marshall Islands', 'not_specified'),
('MR', 'Mauritania', 'not_specified'),
('MU', 'Mauritius', 'not_specified'),
('MX', 'Mexico', 'not_specified'),
('FM', 'Micronesia', 'not_specified'),
('MD', 'Moldova', 'not_specified'),
('MC', 'Monaco', 'not_specified'),
('MN', 'Mongolia', 'not_specified'),
('ME', 'Montenegro', 'not_specified'),
('MA', 'Morocco', 'not_specified'),
('MZ', 'Mozambique', 'not_specified'),
('MM', 'Myanmar', 'not_specified'),
('NA', 'Namibia', 'not_specified'),
('NR', 'Nauru', 'not_specified'),
('NP', 'Nepal', 'not_specified'),
('NL', 'Netherlands', 'not_specified'),
('NZ', 'New Zealand', 'not_specified'),
('NI', 'Nicaragua', 'not_specified'),
('NE', 'Niger', 'not_specified'),
('NG', 'Nigeria', 'not_specified'),
('KP', 'North Korea', 'not_specified'),
('MK', 'North Macedonia', 'not_specified'),
('NO', 'Norway', 'not_specified'),
('OM', 'Oman', 'not_specified'),
('PK', 'Pakistan', 'not_specified'),
('PW', 'Palau', 'not_specified'),
('PA', 'Panama', 'not_specified'),
('PG', 'Papua New Guinea', 'not_specified'),
('PY', 'Paraguay', 'not_specified'),
('PE', 'Peru', 'not_specified'),
('PH', 'Philippines', 'not_specified'),
('PL', 'Poland', 'not_specified'),
('PT', 'Portugal', 'not_specified'),
('QA', 'Qatar', 'not_specified'),
('RO', 'Romania', 'not_specified'),
('RU', 'Russia', 'not_specified'),
('RW', 'Rwanda', 'not_specified'),
('KN', 'Saint Kitts and Nevis', 'not_specified'),
('LC', 'Saint Lucia', 'not_specified'),
('VC', 'Saint Vincent and the Grenadines', 'not_specified'),
('WS', 'Samoa', 'not_specified'),
('SM', 'San Marino', 'not_specified'),
('ST', 'Sao Tome and Principe', 'not_specified'),
('SA', 'Saudi Arabia', 'not_specified'),
('SN', 'Senegal', 'not_specified'),
('RS', 'Serbia', 'not_specified'),
('SC', 'Seychelles', 'not_specified'),
('SL', 'Sierra Leone', 'not_specified'),
('SG', 'Singapore', 'not_specified'),
('SK', 'Slovakia', 'not_specified'),
('SI', 'Slovenia', 'not_specified'),
('SB', 'Solomon Islands', 'not_specified'),
('SO', 'Somalia', 'not_specified'),
('ZA', 'South Africa', 'not_specified'),
('SS', 'South Sudan', 'not_specified'),
('ES', 'Spain', 'not_specified'),
('LK', 'Sri Lanka', 'not_specified'),
('SD', 'Sudan', 'not_specified'),
('SR', 'Suriname', 'not_specified'),
('SE', 'Sweden', 'not_specified'),
('CH', 'Switzerland', 'not_specified'),
('SY', 'Syria', 'not_specified'),
('TW', 'Taiwan', 'not_specified'),
('TJ', 'Tajikistan', 'not_specified'),
('TZ', 'Tanzania', 'not_specified'),
('TH', 'Thailand', 'not_specified'),
('TL', 'Timor-Leste', 'not_specified'),
('TG', 'Togo', 'not_specified'),
('TO', 'Tonga', 'not_specified'),
('TT', 'Trinidad and Tobago', 'not_specified'),
('TN', 'Tunisia', 'not_specified'),
('TR', 'Turkey', 'not_specified'),
('TM', 'Turkmenistan', 'not_specified'),
('TV', 'Tuvalu', 'not_specified'),
('UG', 'Uganda', 'not_specified'),
('UA', 'Ukraine', 'not_specified'),
('AE', 'United Arab Emirates', 'not_specified'),
('GB', 'United Kingdom', 'not_specified'),
('US', 'United States', 'not_specified'),
('UY', 'Uruguay', 'not_specified'),
('UZ', 'Uzbekistan', 'not_specified'),
('VU', 'Vanuatu', 'not_specified'),
('VE', 'Venezuela', 'not_specified'),
('VN', 'Vietnam', 'not_specified'),
('YE', 'Yemen', 'not_specified'),
('ZM', 'Zambia', 'not_specified'),
('ZW', 'Zimbabwe', 'not_specified');
