-- Clipaza Database Schema
-- Generated by Clipaza Installer

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

-- Users table
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('admin','user','moderator') NOT NULL DEFAULT 'user',
  `status` enum('active','inactive','banned','pending') NOT NULL DEFAULT 'pending',
  `login_notifications` tinyint(1) NOT NULL DEFAULT 0,
  `email_verification_token` varchar(255) DEFAULT NULL,
  `google_id` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_username` (`username`),
  UNIQUE KEY `uq_users_email` (`email`),
  KEY `idx_users_role` (`role`),
  KEY `idx_users_status` (`status`),
  KEY `idx_users_google` (`google_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Site settings
CREATE TABLE IF NOT EXISTS `site_settings` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_site_settings_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Security settings
CREATE TABLE IF NOT EXISTS `security_settings` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_security_settings_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Login attempts
CREATE TABLE IF NOT EXISTS `login_attempts` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `success` tinyint(1) NOT NULL DEFAULT 0,
  `attempted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_login_attempts_username` (`username`),
  KEY `idx_login_attempts_ip` (`ip_address`),
  KEY `idx_login_attempts_at` (`attempted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- IP blocks
CREATE TABLE IF NOT EXISTS `ip_blocks` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(45) NOT NULL,
  `block_type` enum('temporary','permanent') NOT NULL DEFAULT 'temporary',
  `blocked_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `blocked_until` datetime DEFAULT NULL,
  `reason` varchar(500) DEFAULT NULL,
  `created_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ip_blocks_ip` (`ip_address`),
  KEY `idx_ip_blocks_until` (`blocked_until`),
  KEY `fk_ip_blocks_user` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- IP whitelist
CREATE TABLE IF NOT EXISTS `ip_whitelist` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(45) NOT NULL,
  `user_id` int(11) UNSIGNED DEFAULT NULL,
  `successful_logins` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `last_seen` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ip_whitelist_ip` (`ip_address`),
  KEY `fk_ip_whitelist_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Account locks
CREATE TABLE IF NOT EXISTS `account_locks` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `locked_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `locked_until` datetime DEFAULT NULL,
  `lock_reason` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_account_locks_username` (`username`),
  KEY `idx_account_locks_until` (`locked_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Login history
CREATE TABLE IF NOT EXISTS `login_history` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED DEFAULT NULL,
  `username` varchar(100) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `action` varchar(50) NOT NULL,
  `details` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_login_history_user` (`user_id`),
  KEY `idx_login_history_ip` (`ip_address`),
  KEY `idx_login_history_action` (`action`),
  KEY `idx_login_history_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Country rules
CREATE TABLE IF NOT EXISTS `country_rules` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_code` char(2) NOT NULL,
  `country_name` varchar(100) NOT NULL,
  `status` enum('not_specified','whitelist','blacklist') NOT NULL DEFAULT 'not_specified',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_country_rules_code` (`country_code`),
  KEY `idx_country_rules_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Email queue
CREATE TABLE IF NOT EXISTS `email_queue` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `to_email` varchar(255) NOT NULL,
  `subject` varchar(500) NOT NULL,
  `body` text NOT NULL,
  `sent` tinyint(1) NOT NULL DEFAULT 0,
  `attempts` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sent_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_email_queue_sent` (`sent`),
  KEY `idx_email_queue_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Contests
CREATE TABLE IF NOT EXISTS `contests` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `creator_id` int(11) UNSIGNED DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `youtube_url` varchar(2000) DEFAULT NULL,
  `youtube_video_id` varchar(50) DEFAULT NULL,
  `youtube_title` varchar(500) DEFAULT NULL,
  `youtube_thumbnail` varchar(2000) DEFAULT NULL,
  `must_subscribe` tinyint(1) NOT NULL DEFAULT 0,
  `must_like` tinyint(1) NOT NULL DEFAULT 0,
  `must_comment` tinyint(1) NOT NULL DEFAULT 0,
  `clip_start_time` varchar(20) DEFAULT NULL,
  `clip_end_time` varchar(20) DEFAULT NULL,
  `clip_instructions` text DEFAULT NULL,
  `prize_pool` decimal(12,2) NOT NULL DEFAULT 0.00,
  `platform_fee` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` enum('draft','active','ended','cancelled') NOT NULL DEFAULT 'draft',
  `escrow_status` enum('unfunded','funded','released','refunded') NOT NULL DEFAULT 'unfunded',
  `winner_takes_all` tinyint(1) NOT NULL DEFAULT 0,
  `paystack_reference` varchar(255) DEFAULT NULL,
  `payhub_reference` varchar(255) DEFAULT NULL,
  `start_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_featured` tinyint(1) NOT NULL DEFAULT 0,
  `featured_until` datetime DEFAULT NULL,
  `featured_plan_id` int(11) UNSIGNED DEFAULT NULL,
  `featured_payment_ref` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_contests_status` (`status`),
  KEY `idx_contests_dates` (`start_date`, `end_date`),
  KEY `idx_contests_creator` (`creator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Contest entries
CREATE TABLE IF NOT EXISTS `contest_entries` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contest_id` int(11) UNSIGNED NOT NULL,
  `user_id` int(11) UNSIGNED NOT NULL,
  `clip_url` varchar(2000) NOT NULL,
  `platform` enum('tiktok','instagram','facebook') DEFAULT NULL,
  `view_count` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `like_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `comment_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `votes` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `disqualified` tinyint(1) NOT NULL DEFAULT 0,
  `disqualify_reason` varchar(255) DEFAULT NULL,
  `verified_subscribe` tinyint(1) NOT NULL DEFAULT 0,
  `verified_like` tinyint(1) NOT NULL DEFAULT 0,
  `verified_comment` tinyint(1) NOT NULL DEFAULT 0,
  `rank_position` int(10) UNSIGNED DEFAULT NULL,
  `proof_subscribe_path` varchar(500) DEFAULT NULL,
  `proof_comment_path` varchar(500) DEFAULT NULL,
  `proof_like_path` varchar(500) DEFAULT NULL,
  `bot_score` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `bot_flags` varchar(1000) DEFAULT NULL,
  `submission_ip` varchar(45) DEFAULT NULL,
  `submission_ua` varchar(500) DEFAULT NULL,
  `proof_video_path` varchar(500) DEFAULT NULL,
  `submitted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_entries_contest` (`contest_id`),
  KEY `fk_entries_user` (`user_id`),
  KEY `idx_entries_status` (`status`),
  KEY `idx_entries_platform` (`platform`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Transactions
CREATE TABLE IF NOT EXISTS `transactions` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `type` enum('credit','debit','withdrawal','refund') NOT NULL,
  `status` enum('pending','completed','failed','cancelled') NOT NULL DEFAULT 'pending',
  `reference` varchar(255) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_transactions_user` (`user_id`),
  KEY `idx_transactions_type` (`type`),
  KEY `idx_transactions_status` (`status`),
  KEY `idx_transactions_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Waitlist
CREATE TABLE IF NOT EXISTS `waitlist` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_waitlist_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User profiles (extends users table)
CREATE TABLE IF NOT EXISTS `user_profiles` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED NOT NULL,
  `display_name` varchar(100) DEFAULT NULL,
  `bio` text DEFAULT NULL,
  `youtube_handle` varchar(100) DEFAULT NULL,
  `youtube_channel_id` varchar(100) DEFAULT NULL,
  `tiktok_handle` varchar(100) DEFAULT NULL,
  `instagram_handle` varchar(100) DEFAULT NULL,
  `facebook_handle` varchar(100) DEFAULT NULL,
  `active_mode` enum('creator','clipper') NOT NULL DEFAULT 'clipper',
  `wallet_balance` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_earned` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_spent` decimal(12,2) NOT NULL DEFAULT 0.00,
  `avatar` varchar(500) DEFAULT NULL,
  `kyc_status` enum('none', 'pending', 'approved', 'rejected') NOT NULL DEFAULT 'none',
  `kyc_id_type` varchar(50) DEFAULT NULL,
  `kyc_id_path` varchar(255) DEFAULT NULL,
  `kyc_snapshot_path` varchar(255) DEFAULT NULL,
  `kyc_id_expiry` date DEFAULT NULL,
  `kyc_rejection_reason` text DEFAULT NULL,
  `bank_name` varchar(100) DEFAULT NULL,
  `bank_code` varchar(20) DEFAULT NULL,
  `account_number` varchar(20) DEFAULT NULL,
  `account_name` varchar(200) DEFAULT NULL,
  `brand_description` text DEFAULT NULL,
  `disclaimer_accepted` tinyint(1) NOT NULL DEFAULT 0,
  `disclaimer_accepted_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_profiles_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Contest platform prize splits
CREATE TABLE IF NOT EXISTS `contest_platforms` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contest_id` int(11) UNSIGNED NOT NULL,
  `platform` enum('tiktok','instagram','facebook') NOT NULL,
  `prize_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `winner_count` int(11) UNSIGNED NOT NULL DEFAULT 3,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_contest_platform` (`contest_id`,`platform`),
  KEY `idx_cp_contest` (`contest_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Payouts (winner prize claims)
CREATE TABLE IF NOT EXISTS `payouts` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contest_id` int(11) UNSIGNED NOT NULL,
  `user_id` int(11) UNSIGNED NOT NULL,
  `entry_id` int(11) UNSIGNED NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `platform` enum('tiktok','instagram','facebook') NOT NULL,
  `rank_position` int(11) UNSIGNED NOT NULL DEFAULT 1,
  `status` enum('pending','claimed','processing','completed','failed','rejected','cancelled') NOT NULL DEFAULT 'pending',
  `rejection_reason` text DEFAULT NULL,
  `appeal_message` text DEFAULT NULL,
  `bank_name` varchar(200) DEFAULT NULL,
  `bank_code` varchar(20) DEFAULT NULL,
  `account_number` varchar(20) DEFAULT NULL,
  `account_name` varchar(200) DEFAULT NULL,
  `nuban_verified` tinyint(1) NOT NULL DEFAULT 0,
  `paystack_reference` varchar(255) DEFAULT NULL,
  `paystack_transfer_code` varchar(255) DEFAULT NULL,
  `claimed_at` datetime DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_payouts_contest` (`contest_id`),
  KEY `idx_payouts_user` (`user_id`),
  KEY `idx_payouts_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Email verifications
CREATE TABLE IF NOT EXISTS `email_verifications` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED NOT NULL,
  `token` varchar(100) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ev_token` (`token`),
  KEY `idx_ev_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Password reset tokens
CREATE TABLE IF NOT EXISTS `password_resets` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `token` varchar(100) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_pr_token` (`token`),
  KEY `idx_pr_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Default security settings
INSERT INTO `security_settings` (`setting_key`, `setting_value`) VALUES
('ip_protection_enabled', '1'),
('ip_period_minutes', '15'),
('ip_max_failures', '10'),
('username_protection_enabled', '1'),
('username_period_minutes', '30'),
('username_max_failures', '5'),
('block_duration_minutes', '60'),
('notify_on_block', '1'),
('notify_on_lock', '1'),
('log_retention_days', '90'),
('two_factor_enabled', '0'),
('captcha_enabled', '0'),
('captcha_threshold', '3'),
('protect_local_only', '0'),
('allow_lock_admin', '0'),
('ip_block_duration_option', '1day'),
('notify_admin_login_unknown_ip', '0'),
('notify_brute_force_with_username', '0')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);

-- Default site settings
INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES
('site_name', 'Clipaza'),
('site_url', 'http://localhost'),
('admin_email', 'admin@example.com'),
('maintenance_mode', '0'),
('registration_enabled', '1'),
('timezone', 'UTC'),
('site_logo', ''),
('site_favicon', ''),
('seo_title', ''),
('seo_description', ''),
('seo_keywords', ''),
('og_image_url', ''),
('custom_header_code', ''),
('adsense_code', ''),
('ads_txt_content', '')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);

-- Additional site settings for payment/contest features
INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES
('paystack_public_key', ''),
('paystack_secret_key', ''),
('platform_fee_percent', '10'),
('youtube_api_key', ''),
('min_contest_prize', '5000'),
('max_contest_days', '30'),
('google_client_id', ''),
('google_client_secret', ''),
('cron_key', 'default_cron_key_123')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);

-- Notifications
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED NOT NULL,
  `type` varchar(50) NOT NULL DEFAULT 'info',
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `link` varchar(500) DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_notif_user` (`user_id`),
  KEY `idx_notif_read` (`is_read`),
  KEY `idx_notif_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Payout requests (wallet withdrawals)
CREATE TABLE IF NOT EXISTS `payout_requests` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `status` enum('pending','approved','rejected','cancelled','on_hold') NOT NULL DEFAULT 'pending',
  `bank_name` varchar(200) DEFAULT NULL,
  `bank_code` varchar(20) DEFAULT NULL,
  `account_number` varchar(20) DEFAULT NULL,
  `account_name` varchar(200) DEFAULT NULL,
  `rejection_reason` text DEFAULT NULL,
  `cancel_reason` text DEFAULT NULL,
  `appeal_message` text DEFAULT NULL,
  `admin_note` text DEFAULT NULL,
  `paystack_reference` varchar(255) DEFAULT NULL,
  `paystack_transfer_code` varchar(255) DEFAULT NULL,
  `processed_by` int(11) UNSIGNED DEFAULT NULL,
  `processed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pr_user` (`user_id`),
  KEY `idx_pr_status` (`status`),
  KEY `idx_pr_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Additional site settings for new features
INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES
('paystack_fee_percent', '0'),
('paystack_fee_flat', '0'),
('min_withdrawal_amount', '1000'),
('max_withdrawal_amount', '500000'),
('withdrawal_fee_percent', '0'),
('withdrawal_fee_flat', '0')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);

-- Ad packages (admin-created advertising plans)
CREATE TABLE IF NOT EXISTS `ad_packages` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `price` decimal(12,2) NOT NULL,
  `duration_days` int(11) UNSIGNED NOT NULL DEFAULT 30,
  `features` text DEFAULT NULL COMMENT 'JSON array of feature strings',
  `placement_zones` varchar(500) DEFAULT NULL COMMENT 'JSON array: homepage, contests, sidebar etc',
  `max_ads` int(11) UNSIGNED NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `sort_order` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ap_active` (`is_active`),
  KEY `idx_ap_sort` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Movie ads (creator submissions)
CREATE TABLE IF NOT EXISTS `movie_ads` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED NOT NULL,
  `package_id` int(11) UNSIGNED NOT NULL,
  `movie_title` varchar(255) NOT NULL,
  `tagline` varchar(500) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `genre` varchar(100) DEFAULT NULL,
  `release_date` date DEFAULT NULL,
  `trailer_url` varchar(2000) DEFAULT NULL COMMENT 'YouTube/video URL for preview',
  `poster_path` varchar(500) DEFAULT NULL COMMENT 'Uploaded movie poster/e-flyer',
  `flyer_path` varchar(500) DEFAULT NULL COMMENT 'Uploaded e-flyer image',
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_phone` varchar(30) DEFAULT NULL,
  `website_url` varchar(2000) DEFAULT NULL,
  `payment_method` enum('online','manual') NOT NULL DEFAULT 'online',
  `payment_status` enum('unpaid','pending_verification','paid') NOT NULL DEFAULT 'unpaid',
  `payment_reference` varchar(255) DEFAULT NULL,
  `manual_deposit_proof` varchar(500) DEFAULT NULL COMMENT 'Uploaded proof of bank transfer',
  `manual_deposit_amount` decimal(12,2) DEFAULT NULL,
  `manual_deposit_note` text DEFAULT NULL,
  `status` enum('draft','pending_review','approved','rejected','expired','cancelled') NOT NULL DEFAULT 'draft',
  `review_note` text DEFAULT NULL,
  `reviewed_by` int(11) UNSIGNED DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `starts_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `impression_count` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ma_user` (`user_id`),
  KEY `idx_ma_package` (`package_id`),
  KEY `idx_ma_status` (`status`),
  KEY `idx_ma_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Ad bank account settings
INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES
('ad_bank_name', ''),
('ad_bank_account', ''),
('ad_bank_number', ''),
('payhub_base_url', 'https://payhub.datagifting.com.ng'),
('payhub_api_key', ''),
('payhub_merchant_id', ''),
('preferred_payout_gateway', 'paystack')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);

-- PayHub virtual accounts
CREATE TABLE IF NOT EXISTS `payhub_virtual_accounts` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) UNSIGNED NOT NULL,
  `account_number` varchar(20) NOT NULL,
  `account_name` varchar(255) NOT NULL,
  `bank_name` varchar(255) NOT NULL,
  `payhub_reference` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_pva_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `featured_contest_plans` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `duration_days` int(11) NOT NULL DEFAULT 7,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET foreign_key_checks = 1;
